guardy:

    # Publish all joint states -----------------------------------
    joint_state_controller:
      type: joint_state_controller/JointStateController
      publish_rate: 50
      
    upperlegM1_joint_position_controller:
      type: effort_controllers/JointPositionController
      joint: head_upperlegM1_joint
      pid: {p: 3.0, i: 1.0, d: 0.0}
    upperlegM2_joint_position_controller:
      type: effort_controllers/JointPositionController
      joint: head_upperlegM2_joint
      pid: {p: 3.0, i: 1.0, d: 0.0}
    upperlegM3_joint_position_controller:
      type: effort_controllers/JointPositionController
      joint: head_upperlegM3_joint
      pid: {p: 3.0, i: 1.0, d: 0.0}
      
    lowerlegM1_joint_position_controller:
      type: effort_controllers/JointPositionController
      joint: lower_legM1_joint
      pid: {p: 3.0, i: 1.0, d: 0.0}
    lowerlegM2_joint_position_controller:
      type: effort_controllers/JointPositionController
      joint: lower_legM2_joint
      pid: {p: 3.0, i: 1.0, d: 0.0}
    lowerlegM3_joint_position_controller:
      type: effort_controllers/JointPositionController
      joint: lower_legM3_joint
      pid: {p: 3.0, i: 1.0, d: 0.0}

